package com.vaultify.vaultify_backend.model;

public enum AuditAction {
    LOGIN,
    CREATE_BUSINESS,
    UPDATE_BUSINESS_SUBSCRIPTION,
    UPDATE_BUSINESS_STATUS,
    CREATE_STAFF,
    UPDATE_STAFF,
    DISABLE_STAFF,
    CREATE_CLIENT,
    UPDATE_CLIENT,
    DISABLE_CLIENT,
    CREATE_SERVICE,
    UPDATE_SERVICE,
    DISABLE_SERVICE,
    CREATE_APPOINTMENT,
    UPDATE_APPOINTMENT,
    CANCEL_APPOINTMENT,
    UPDATE_PROFILE,
    UPDATE_PASSWORD
}
